### ISSUE TITLE
Animations are too quick and look like a drawing glitch

### ISSUE THREAD

**Issue by tinoucas** [mereed/pebbleface-taller-colour#1]
It would be really nice to have the animation slower, or a setting to disable it altogether.

I first thought it was a glitch in the drawing but only replacing the (animation) bool argument of all window_stack_push() calls to false makes the whole watchface appearance rock solid.

**Comment by mereed** [comment]
hi, there isn't any animation.  i think what you're referring to is when the screen redraws when say changing colour/settings.  i might have a better way of doing it so that nothing is noticeable.  i was sort of forcing it so that users wouldn't have to wait until the next minute for a screen redraw.

**Comment by mereed** [comment]
i've done an update - it shouldn't be noticeable now when changing colour.

**Comment by tinoucas** [comment]
Yes, I see the improvement.

I didn't see any new commit on github, I was curious to what changes you
chose to apply for this.

As a side note, I'm not quite fan of the new "7" look though.

Étienne

**Comment by mereed** [comment]
sorry, just updating github now.

with the new 7 i'm trying to minimise the pixely look it had with the prior style.  as the time is made up of images, it's very difficult to apply colour to an aliased image. i'm aliasing the numbers for my 'big black' watchface, but not doing any colour change.

**Comment by mereed** [comment]
select from orig and new font
